<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Caloy</title>
    <!-- Bootstrap -->
    <link href="../css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../style.css">
    <link href='https://fonts.googleapis.com/css?family=Passion+One|Raleway:400,300,500italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	<style type="text/css">
		#main-header{
			margin-top:200px;
		}
	</style>
  </head>
  <body id="myPage" data-offset="60">
    <header id="main-header">
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="../index.html">CALOY</a>
          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="../index.html">Home</a></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
	
<?php 
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$neg = 0;
	$pos = 0;
	$neut = 0;
	$max = 0;
	$status = "";
	$item = $_POST['item'];
	
	for($x = 0; $x < 20; $x++){
		// Read the file contents into a string variable,
		// and parse the string into a data structure
		$str_data = file_get_contents("test1.json");
		$data = json_decode($str_data,true);
		 
		//var_dump(sizeof($data["tweets"][0]["text"]));

		//$count = sizeof($data["tweets"]);

		//echo "<br />";
		//echo "Text: ".$data["tweets"];
		
		$ch = curl_init();
		$text = $data["tweets"][$x]["text"];
		
		curl_setopt($ch, CURLOPT_URL, "http://text-processing.com/api/sentiment/");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "text=$text");
		curl_setopt($ch, CURLOPT_POST, 1);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			echo 'Error:' . curl_error($ch);
		}
		
		//$obj = json_decode($result,true);
		//var_dump($obj);
		curl_close ($ch);
	
		$data = json_decode( $result, true );
		if($data["label"] == "neg"){
			$neg++;
		}else if($data["label"] == "pos"){
			$pos++;
		}else if($data["label"] == "neutral"){
			$neut++;
		}
	}
		
	//echo $data["label"]." - ".$neut."<br />";
	if($pos > $max){
		$max = $pos;
		$status = "Positive";
	}else if($neg > $max){
		$max = $neg;
		$status = "Negative";
	}else if($neut > $max){
		$max = $neut;
		$status = "Neutral";
	}
	echo "<div class='well' style='
		margin-left:80px; margin-right:80px;
		text-align:center;
	'>";
	echo "<h1 style='font-size:40px;'>People are <b style='font-weight:bold;'>".$status."</b> about ".$item.".</h1>";
	echo "</div>";
	
	echo "<pre>";
	convertJSONtoArray( $data, 0 );
	echo "</pre>";
	
	function convertJSONtoArray( $data, $level )  // level - ??????? ??????????? ????? ????????? ?????? ??????????
	{
		foreach( $data as $key1 => $value1 )
		{
			if( is_array( $value1 ) )
			{
				//echo str_repeat( "\t", $level ) . '["' . $key1 . '"] => array (' . "\n";
				convertJSONtoArray( $value1, $level + 1 );
				//echo str_repeat( "\t", $level ) . ")," . "\n";
			}
			else
			{
				if( ( $value1=='true' ) or ( $value1=='false' ) or ( is_numeric( $value1 ) ) )  // if numeris or boolean we dont'add quotes
				{
					//echo str_repeat( "\t", $level ) . '["' . $key1 . '"] => ' . $value1 . ',' . "\n";
				}
				else
				{
					//echo str_repeat( "\t", $level ) . '["' . $key1 . '"] => "' . $value1 . '",' . "\n";
				}
			}
		}
	}
	
?>
 <footer id="main-footer">
      <div class="container">
        <div class="row">
          <p class="white">2016 HexDev.</p>
        </div>
      </div>
    </footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="../js/bootstrap.min.js"></script>
    <!-- bxSlider Javascript file -->
    <script src=""></script>
      <script>


         $(document).ready(function(){
        $('.bxslider').bxSlider();
      });

      </script>
      <script>
$(document).ready(function(){
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

  // Prevent default anchor click behavior
  event.preventDefault();

  // Store hash
  var hash = this.hash;

  // Using jQuery's animate() method to add smooth page scroll
  // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
  $('html, body').animate({
    scrollTop: $(hash).offset().top
  }, 900, function(){

    // Add hash (#) to URL when done scrolling (default click behavior)
    window.location.hash = hash;
    });
  });
})
</script>
  </body>
</html>